include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    file_names: ignore

linter:
  rules:
    always_specify_types: true
    unnecessary_new: false
    prefer_single_quotes: true
    public_member_api_docs: true

