name: number_to_thai_words
description: A Dart package to convert numbers to Thai words.
version: 1.0.0
homepage: https://github.com/thisadee2897/number_to_thai_words

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  example: example/