name: number_to_thai_words
description: |
  A Dart package that converts numeric values into their corresponding Thai word representation.

version: 1.0.5
homepage: https://github.com/thisadee2897/number_to_thai_words
repository: https://github.com/thisadee2897/number_to_thai_words

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
  web:
  linux:
  macos:
  windows: